### ISSUE TITLE
Add backend services launch type

### ISSUE THREAD

**Issue by vlad-ignatov** [smart-on-fhir/smart-launcher-v2#2]
@jmandel wrote:
> Feature note: I think we *do* want a "Backend Services Launch" option. Now that we've folded Backed Services into the core SMART spec (e.g. in overview at [https://hl7.org/fhir/smart-app-launch/](https://urldefense.com/v3/__https://hl7.org/fhir/smart-app-launch/__;!!NZvER7FxgEiBAiR_!t-amiz1vlE_nJ2XDrpdNSD14qAvxMXLG9NIVPd8P7JAJqSyEAHjb1n_-H1TaiEo3POxPyHcxk8RdesFWVKbq9Z0b6aZLBqnQ$)) it'll be important to support testing of this functionality. Basic workflow would be: choose "launch type" of "Backend Services", and get a "FHIR base URL" at the bottom of the launcher, just like in a standalone launch. Now apps can  POST directly to the /token endpoint with a client authn JWT + scopes to obtain an access token. It's the same workflow that the bulk data tool already supports, but will allow developers to try out a flow where they get scopes like `system/Patient.read` and then can make API calls like `GET /Patient?name=...` which will be important for folks developing headless EHR-integrated services. Does this make sense?

**Comment by vlad-ignatov** [comment]
OK, I have deployed  some changes, adding support for BS launch as well as separate sample app for that.

**Comment by jmandel** [comment]
This is looking great!

One issue on validation: if I set "JWKS Inline" via the "App Registration Options" tab, and then launch the sample app, it proceeds with a different public key (e.g., its default value from https://www.hl7.org/fhir/smart-app-launch/RS384.public.json). I'd expect this token request to *fail* because the app-supplied JKU is only a "hint"; the server can't trust it or treat it as authoritative, if it's inconsistent with the registration-time JWKS or JWKS URI. Does this make sense?

**Comment by vlad-ignatov** [comment]
I am trying to figure out the proper behavior (applies to both backend service launch and asymmetric auth). Is this correct and what should be done if we have `jwks + jku` (case 6)?

```
# | jwks | jwks_url | jku |
--+------+----------+-----+-----------------------------------------
1 |  N   |    N     |  N  |  Not OK
2 |  N   |    N     |  Y  |  OK if jku works
3 |  N   |    Y     |  N  |  OK if jwks_url works
4 |  Y   |    N     |  N  |  OK if jwks works
5 |  N   |    Y     |  Y  |  OK if jwks_url works and matches jku
6 |  Y   |    N     |  Y  |  ?
7 |  Y   |    Y     |  N  |  OK if jwks_url works; Ignore jwks
8 |  Y   |    Y     |  Y  |  OK if jwks_url works and matches jku; Ignore jwks
```

**Comment by jmandel** [comment]
Thanks for laying this out in a logical grid!

Let me try to build up from a processing model. When a token request arrives...

* If neither `jwks` nor `jwks_uri` is set in "App Registration Options", disable client authn checks. Just make sure a well-formed JWS is present in the client assertion, and consider it "valid" if so. (This is similar to how we disable client authn checks for symmetric authn, if no client secret is set in app registration.)

* Otherwise, enable client authn checks.
  * Build a set of "allowed keys" as the union of:
    * All keys in `jwks`
    * All keys in `jwks_uri`
  * Check whether the JWS is valid and signed with one of the allowed keys
  * If `jku` is present as a JWS header, check that an idential `jwks_uri` was included in "App Registration" options, because https://hl7.org/fhir/smart-app-launch/client-confidential-asymmetric.html says: "When present, this SHALL match the JWKS URL value that the client supplied to the FHIR authorization server at client registration time."

**Comment by vlad-ignatov** [comment]
It says [here](http://www.hl7.org/fhir/smart-app-launch/client-confidential-asymmetric.html#signature-verification) that "If no keys match, or more than one key matches, the verification fails.". There is an edge case where the user enters a `jwks` and a `jwks_url` that provides the same JWKS. In this case we will have duplicate keys. What is the correct behavior then?
- a. Ignore duplicates (if so, how can we have more than one match?)
- b. Prefer keys from jwks_uri as they may be more recent
- c. Produce an error

Is it even valid to use `jwks` and `jwks_uri` together?

**Comment by jmandel** [comment]
> an edge case where the user enters a jwks and a jwks_url that provides the same JWKS. 

Just to be clear, you're saying the JWKS and the JWKS URL are both provided and *both* have a key with the same `kid`? Sure, in that case we should produce an error (not sure it's the "best" behavior but it's what the spec says, so seems good enough). Note that this issues doesn't arise when the JWKS and JWKS URL have content with distinct `kid`s.

**Comment by jmandel** [comment]
That sounds great, thanks @vlad-ignatov !
